(function () {
	'use strict';

	var Logger=function(){function n(){}return n.init=function(o){n._plugin=o;},n.log=function(o){n._plugin.broadcastMessage("log",o);},n.error=function(o){n._plugin.broadcastMessage("error",o);},n}();

	var Coroutine=function(){function t(t,e){this._elapsedTime=0,this._coroutineIterator=t,this._currentYieldInstruction=null,this._isCurrenYieldInstructionExist=!1,this._onFinish=null!=e?e:null;}return Object.defineProperty(t.prototype,"elapsedTime",{get:function(){return this._elapsedTime},set:function(t){this._elapsedTime=t;},enumerable:!1,configurable:!0}),Object.defineProperty(t.prototype,"currentYieldInstruction",{get:function(){return this._currentYieldInstruction},enumerable:!1,configurable:!0}),Object.defineProperty(t.prototype,"currentYieldInstructionExist",{get:function(){return this._isCurrenYieldInstructionExist},enumerable:!1,configurable:!0}),t.prototype.fatchNextInstruction=function(){var t,e=this._coroutineIterator.next();return e.done?(this._currentYieldInstruction=null,this._isCurrenYieldInstructionExist=!1,null===(t=this._onFinish)||void 0===t||t.call(this),this._onFinish=null,null):(this._currentYieldInstruction=e.value,this._isCurrenYieldInstructionExist=!0,this._currentYieldInstruction)},t}();

	var __extends=this&&this.__extends||function(){var t=function(e,n){return t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e;}||function(t,e){for(var n in e)Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);},t(e,n)};return function(e,n){if("function"!=typeof n&&null!==n)throw new TypeError("Class extends value "+String(n)+" is not a constructor or null");function r(){this.constructor=e;}t(e,n),e.prototype=null===n?Object.create(n):(r.prototype=n.prototype,new r);}}(),YieldInstruction=function(){};var WaitForSeconds=function(t){function e(e){var n=t.call(this)||this;return n._seconds=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"seconds",{get:function(){return this._seconds},enumerable:!1,configurable:!0}),e}(YieldInstruction);var WaitUntil=function(t){function e(e){var n=t.call(this)||this;return n._predicate=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"predicate",{get:function(){return this._predicate},enumerable:!1,configurable:!0}),e}(YieldInstruction);var WaitWhile=function(t){function e(e){var n=t.call(this)||this;return n._predicate=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"predicate",{get:function(){return this._predicate},enumerable:!1,configurable:!0}),e}(YieldInstruction);

	var CoroutineProcessor=function(){function t(t){this._time=t,this._coroutines=[],this._coroutineCount=0;}return t.prototype.addCoroutine=function(t){this._coroutines.push(t),this._coroutineCount+=1;},t.prototype.removeCoroutine=function(t){var o=this._coroutines.indexOf(t);o>=0&&(this._coroutines[o]=null,this._coroutineCount-=1);},t.prototype.tryCompact=function(){var o=this._coroutines;if(t._needToCompactCount<=o.length-this._coroutineCount){for(var n=0,e=0;e<o.length;++e){var i=o[e];null!==i&&(o[n]=i,n+=1);}o.length=this._coroutineCount;}},t.prototype.process=function(){for(var t=this._coroutines,o=0;o<t.length;++o){var n=t[o];null!==n&&(n.currentYieldInstructionExist?this.updateAfterProcessSingleInstruction(n):(t[o]=null,this._coroutineCount-=1));}},t.prototype.updateAfterProcessSingleInstruction=function(t){var o=t.currentYieldInstruction;o instanceof WaitForSeconds?(t.elapsedTime+=this._time.deltaTime,t.elapsedTime>=o.seconds&&(t.elapsedTime=0,t.fatchNextInstruction())):o instanceof WaitUntil?o.predicate()&&t.fatchNextInstruction():o instanceof WaitWhile?o.predicate()||t.fatchNextInstruction():null===o&&t.fatchNextInstruction();},t._needToCompactCount=16,t}();

	var Time=function(){function e(){this._oldTime=0,this._time=0,this._unscaledTime=0,this._deltaTime=0,this._unscaledDeltaTime=0,this._timeScale=1;}return e.prototype.start=function(){this._oldTime=Date.now();},e.prototype.update=function(){var e=Date.now(),t=(e-this._oldTime)/1e3;this._unscaledDeltaTime=t,this._unscaledTime+=t,this._deltaTime=t*this._timeScale,this._time+=this._deltaTime,this._oldTime=e;},Object.defineProperty(e.prototype,"time",{get:function(){return this._time},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"unscaledTime",{get:function(){return this._unscaledTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"deltaTime",{get:function(){return this._deltaTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"unscaledDeltaTime",{get:function(){return this._unscaledDeltaTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"timeScale",{get:function(){return this._timeScale},set:function(e){this._timeScale=e;},enumerable:!1,configurable:!0}),e}();

	var CoroutineDispatcher=function(){function o(o){void 0===o&&(o=10);var t=this;this._setTimeoutlId=null,this.update=function(){t._time.update(),t._coroutineProcessor.process(),t._coroutineProcessor.tryCompact();};var e=this._time=new Time;this._coroutineProcessor=new CoroutineProcessor(e),e.start();var r=function(){t._setTimeoutlId=setTimeout((function(){r();}),o);try{t.update();}catch(o){Logger.error("".concat(o.message,"\n").concat(o.stack));}};r();}return o.prototype.startCoroutine=function(o){var t=new Coroutine(o);return t.fatchNextInstruction(),this._coroutineProcessor.addCoroutine(t),t},o.prototype.stopCoroutine=function(o){this._coroutineProcessor.removeCoroutine(o);},o.prototype.dispose=function(){null!==this._setTimeoutlId&&(clearTimeout(this._setTimeoutlId),this._setTimeoutlId=null);},o}();

	var Mulberry32=function(){function t(t){this._a=t;}return t.prototype.next=function(){var t=this._a+=1831565813;return t=Math.imul(t^t>>>15,1|t),(((t^=t+Math.imul(t^t>>>7,61|t))^t>>>14)>>>0)/4294967296},t}();

	var Vector2=function(){function t(t,e){void 0===t&&(t=0),void 0===e&&(e=0),this.x=t,this.y=e;}return t.prototype.freeze=function(){return Object.freeze(this)},t.prototype.copy=function(t){return this.x=t.x,this.y=t.y,this},t.prototype.clone=function(){return new t(this.x,this.y)},t.prototype.set=function(t,e){return this.x=t,this.y=e,this},t.prototype.equals=function(t){return this.x===t.x&&this.y===t.y},t.prototype.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)},t.prototype.lengthSquared=function(){return this.x*this.x+this.y*this.y},t}();

	var GridCell=function(e,r){this.x=e,this.y=r,this.visited=!1,this.walls=[!0,!0,!0,!0];},MazeGenerator=function(){function e(e){this._spawnedTiles=[],this._spawnedColliders=[],this._world=e;}return e.prototype.generate=function(e,r,t,l){for(var s=new Mulberry32(l),o=[],i=0;i<e;++i){o[i]=[];for(var n=0;n<r;++n)o[i][n]=new GridCell(i,n);}var a=[],h=o[0][0];for(h.visited=!0,a.push(h);a.length>0;){var p=a[a.length-1],d=this.getNeighbors(o,p);if(d.length>0){var w=d[Math.floor(s.next()*d.length)];this.removeWalls(p,w),w.visited=!0,a.push(w);}else a.pop();}var f=this.gridCellsToBlocks(o);for(i=0;i<f.length;++i)for(n=0;n<f[0].length;++n){var u=f[i][n],v=i+t.x,y=n+t.y;this._world.setTile(v,y,40,u?1:0,!1),this._spawnedTiles.push(new Vector2(v,y)),u&&(this._world.setCollider(v,y,!0),this._spawnedColliders.push(new Vector2(v,y)));}},e.prototype.clear=function(){for(var e=this._spawnedTiles,r=0;r<e.length;++r){var t=e[r];this._world.deleteTile(t.x,t.y,!1);}e.length=0;var l=this._spawnedColliders;for(r=0;r<l.length;++r){var s=l[r];this._world.setCollider(s.x,s.y,!1);}},e.prototype.getNeighbors=function(e,r){var t,l=[];r.x>0&&((t=e[r.x-1][r.y]).visited||l.push(t));r.x<e.length-1&&((t=e[r.x+1][r.y]).visited||l.push(t));r.y>0&&((t=e[r.x][r.y-1]).visited||l.push(t));r.y<e[0].length-1&&((t=e[r.x][r.y+1]).visited||l.push(t));return l},e.prototype.removeWalls=function(e,r){r.x<e.x?(e.walls[0]=!1,r.walls[1]=!1):r.x>e.x?(e.walls[1]=!1,r.walls[0]=!1):r.y<e.y?(e.walls[2]=!1,r.walls[3]=!1):r.y>e.y&&(e.walls[3]=!1,r.walls[2]=!1);},e.prototype.gridCellsToBlocks=function(e){for(var r=e.length,t=e[0].length,l=new Array(2*r+1).fill(null).map((function(e){return new Array(2*t+1)})),s=0;s<2*r+1;++s)l[0][s]=!0;for(var o=0;o<2*t+1;++o)l[o][0]=!0;for(s=0;s<r;s++)for(o=0;o<t;o++)l[2*s+1][2*o+1]=!1,l[2*s+2][2*o+1]=e[s][o].walls[1],l[2*s+1][2*o+2]=e[s][o].walls[2],l[2*s+2][2*o+2]=!0;for(s=0;s<2*r+1;++s)l[2*t][s]=!0;for(o=0;o<2*t+1;++o)l[o][2*r]=!0;return l},e}();

	var __extends$1=this&&this.__extends||function(){var e=function(t,r){return e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t;}||function(e,t){for(var r in t)Object.prototype.hasOwnProperty.call(t,r)&&(e[r]=t[r]);},e(t,r)};return function(t,r){if("function"!=typeof r&&null!==r)throw new TypeError("Class extends value "+String(r)+" is not a constructor or null");function o(){this.constructor=t;}e(t,r),t.prototype=null===r?Object.create(r):(o.prototype=r.prototype,new o);}}();var Plugin=function(e){function t(){var t=null!==e&&e.apply(this,arguments)||this;return t._coroutineDispatcher=null,t._mazeGenerator=null,t._mazePosition=new Vector2(0,0),t._mazeSize=new Vector2(10,10),t._seed=0,t}return __extends$1(t,e),t.prototype.onLoad=function(){Logger.init(this);try{this._coroutineDispatcher=new CoroutineDispatcher,this._mazeGenerator=new MazeGenerator(this),this._mazeGenerator.generate(this._mazeSize.x,this._mazeSize.y,this._mazePosition,this._seed);}catch(e){Logger.error("".concat(e.message,"\n").concat(e.stack));}},t.prototype.onUnload=function(){try{this._mazeGenerator.clear(),this._mazeGenerator=null,this._coroutineDispatcher.dispose(),this._coroutineDispatcher=null;}catch(e){Logger.error("".concat(e.message,"\n").concat(e.stack));}},t.prototype.onMessage=function(e,t){for(var r=[],o=2;o<arguments.length;o++)r[o-2]=arguments[o];try{if("request-position"===t?this.sendMessage(e,"position",this._mazePosition):"request-size"===t?this.sendMessage(e,"size",this._mazeSize):"request-seed"===t&&this.sendMessage(e,"seed",this._seed),"position-input"===t){var i=r[0],s=i.x,n=i.y;this._mazePosition.set(s,n),this._mazeGenerator.clear(),this._mazeGenerator.generate(this._mazeSize.x,this._mazeSize.y,this._mazePosition,this._seed);}else if("size-input"===t){var a=r[0];s=a.x,n=a.y;this._mazeSize.set(s,n),this._mazeGenerator.clear(),this._mazeGenerator.generate(this._mazeSize.x,this._mazeSize.y,this._mazePosition,this._seed);}else if("seed-input"===t){var c=r[0];this._seed=c,this._mazeGenerator.clear(),this._mazeGenerator.generate(this._mazeSize.x,this._mazeSize.y,this._mazePosition,this._seed);}}catch(e){Logger.error("".concat(e.message,"\n").concat(e.stack));}},t}(BasePlugin);globalThis.PluginImpl=Plugin;

}());
