(function () {
	'use strict';

	var Logger=function(){function n(){}return n.init=function(o){n._plugin=o;},n.log=function(o){n._plugin.broadcastMessage("log",o);},n.error=function(o){n._plugin.broadcastMessage("error",o);},n}();

	var Coroutine=function(){function t(t,e){this._elapsedTime=0,this._coroutineIterator=t,this._currentYieldInstruction=null,this._isCurrenYieldInstructionExist=!1,this._onFinish=null!=e?e:null;}return Object.defineProperty(t.prototype,"elapsedTime",{get:function(){return this._elapsedTime},set:function(t){this._elapsedTime=t;},enumerable:!1,configurable:!0}),Object.defineProperty(t.prototype,"currentYieldInstruction",{get:function(){return this._currentYieldInstruction},enumerable:!1,configurable:!0}),Object.defineProperty(t.prototype,"currentYieldInstructionExist",{get:function(){return this._isCurrenYieldInstructionExist},enumerable:!1,configurable:!0}),t.prototype.fatchNextInstruction=function(){var t,e=this._coroutineIterator.next();return e.done?(this._currentYieldInstruction=null,this._isCurrenYieldInstructionExist=!1,null===(t=this._onFinish)||void 0===t||t.call(this),this._onFinish=null,null):(this._currentYieldInstruction=e.value,this._isCurrenYieldInstructionExist=!0,this._currentYieldInstruction)},t}();

	var __extends=this&&this.__extends||function(){var t=function(e,n){return t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e;}||function(t,e){for(var n in e)Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);},t(e,n)};return function(e,n){if("function"!=typeof n&&null!==n)throw new TypeError("Class extends value "+String(n)+" is not a constructor or null");function r(){this.constructor=e;}t(e,n),e.prototype=null===n?Object.create(n):(r.prototype=n.prototype,new r);}}(),YieldInstruction=function(){};var WaitForSeconds=function(t){function e(e){var n=t.call(this)||this;return n._seconds=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"seconds",{get:function(){return this._seconds},enumerable:!1,configurable:!0}),e}(YieldInstruction);var WaitUntil=function(t){function e(e){var n=t.call(this)||this;return n._predicate=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"predicate",{get:function(){return this._predicate},enumerable:!1,configurable:!0}),e}(YieldInstruction);var WaitWhile=function(t){function e(e){var n=t.call(this)||this;return n._predicate=e,n}return __extends(e,t),Object.defineProperty(e.prototype,"predicate",{get:function(){return this._predicate},enumerable:!1,configurable:!0}),e}(YieldInstruction);

	var CoroutineProcessor=function(){function t(t){this._time=t,this._coroutines=[],this._coroutineCount=0;}return t.prototype.addCoroutine=function(t){this._coroutines.push(t),this._coroutineCount+=1;},t.prototype.removeCoroutine=function(t){var o=this._coroutines.indexOf(t);o>=0&&(this._coroutines[o]=null,this._coroutineCount-=1);},t.prototype.tryCompact=function(){var o=this._coroutines;if(t._needToCompactCount<=o.length-this._coroutineCount){for(var n=0,e=0;e<o.length;++e){var i=o[e];null!==i&&(o[n]=i,n+=1);}o.length=this._coroutineCount;}},t.prototype.process=function(){for(var t=this._coroutines,o=0;o<t.length;++o){var n=t[o];null!==n&&(n.currentYieldInstructionExist?this.updateAfterProcessSingleInstruction(n):(t[o]=null,this._coroutineCount-=1));}},t.prototype.updateAfterProcessSingleInstruction=function(t){var o=t.currentYieldInstruction;o instanceof WaitForSeconds?(t.elapsedTime+=this._time.deltaTime,t.elapsedTime>=o.seconds&&(t.elapsedTime=0,t.fatchNextInstruction())):o instanceof WaitUntil?o.predicate()&&t.fatchNextInstruction():o instanceof WaitWhile?o.predicate()||t.fatchNextInstruction():null===o&&t.fatchNextInstruction();},t._needToCompactCount=16,t}();

	var Time=function(){function e(){this._oldTime=0,this._time=0,this._unscaledTime=0,this._deltaTime=0,this._unscaledDeltaTime=0,this._timeScale=1;}return e.prototype.start=function(){this._oldTime=Date.now();},e.prototype.update=function(){var e=Date.now(),t=(e-this._oldTime)/1e3;this._unscaledDeltaTime=t,this._unscaledTime+=t,this._deltaTime=t*this._timeScale,this._time+=this._deltaTime,this._oldTime=e;},Object.defineProperty(e.prototype,"time",{get:function(){return this._time},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"unscaledTime",{get:function(){return this._unscaledTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"deltaTime",{get:function(){return this._deltaTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"unscaledDeltaTime",{get:function(){return this._unscaledDeltaTime},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"timeScale",{get:function(){return this._timeScale},set:function(e){this._timeScale=e;},enumerable:!1,configurable:!0}),e}();

	var CoroutineDispatcher=function(){function o(o){void 0===o&&(o=10);var t=this;this._setTimeoutlId=null,this.update=function(){t._time.update(),t._coroutineProcessor.process(),t._coroutineProcessor.tryCompact();};var e=this._time=new Time;this._coroutineProcessor=new CoroutineProcessor(e),e.start();var r=function(){t._setTimeoutlId=setTimeout((function(){r();}),o);try{t.update();}catch(o){Logger.error("".concat(o.message,"\n").concat(o.stack));}};r();}return o.prototype.startCoroutine=function(o){var t=new Coroutine(o);return t.fatchNextInstruction(),this._coroutineProcessor.addCoroutine(t),t},o.prototype.stopCoroutine=function(o){this._coroutineProcessor.removeCoroutine(o);},o.prototype.dispose=function(){null!==this._setTimeoutlId&&(clearTimeout(this._setTimeoutlId),this._setTimeoutlId=null);},o}();

	var __extends$1=this&&this.__extends||function(){var o=function(t,n){return o=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(o,t){o.__proto__=t;}||function(o,t){for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(o[n]=t[n]);},o(t,n)};return function(t,n){if("function"!=typeof n&&null!==n)throw new TypeError("Class extends value "+String(n)+" is not a constructor or null");function r(){this.constructor=t;}o(t,n),t.prototype=null===n?Object.create(n):(r.prototype=n.prototype,new r);}}();var Plugin=function(o){function t(){var t=null!==o&&o.apply(this,arguments)||this;return t._coroutineDispatcher=null,t}return __extends$1(t,o),t.prototype.onLoad=function(){Logger.init(this);try{this._coroutineDispatcher=new CoroutineDispatcher,setTimeout((function(){Logger.log("Hello, world!");}),5e3);}catch(o){Logger.error("".concat(o.message,"\n").concat(o.stack));}},t.prototype.onUnload=function(){try{this._coroutineDispatcher.dispose(),this._coroutineDispatcher=null;}catch(o){Logger.error("".concat(o.message,"\n").concat(o.stack));}},t.prototype.onPlayerMove=function(o,t,n){Logger.log("onPlayerMove: ".concat(o,", ").concat(t,", ").concat(n));},t.prototype.onMessage=function(o,t){for(var n=[],r=2;r<arguments.length;r++)n[r-2]=arguments[r];try{Logger.log("onMessage: ".concat(o,", ").concat(t,", ").concat(n));}catch(o){Logger.error("".concat(o.message,"\n").concat(o.stack));}},t}(BasePlugin);globalThis.PluginImpl=Plugin;

}());
